/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import phonebook.Criteriu_Filtrare;
import phonebook.Criteriu_Ordonare;
import phonebook.Agenda;
import phonebook.Contact;
import phonebook.NrFix;
import phonebook.NrMobil;
import phonebook.NrTel;
import phonebook.PhoneBook;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author gronk the conqueror
 */
public class PhoneBookManager extends javax.swing.JFrame {

    private DefaultListModel<Contact> listaContacte = new DefaultListModel<>();
    private Agenda agenda = new Agenda();
    
    private DefaultComboBoxModel cbFiltrare = new DefaultComboBoxModel(Criteriu_Filtrare.values());
    private DefaultComboBoxModel cbOrdonare = new DefaultComboBoxModel(Criteriu_Ordonare.values());
    
    List<Contact> contacteAfisate = Agenda.getListaContacte();
    /**
     * Creates new form PhoneBookManager
     */
    public PhoneBookManager() {
        initComponents();
        ListaContacte.setModel(listaContacte);
        refreshModel(Agenda.getListaContacte());
        CBFiltrare.setModel(cbFiltrare);
        CBOrdonare.setModel(cbOrdonare);
        btnDeschidere.setEnabled(true);
        btnSalvare.setEnabled(true);
    }
    
    void refreshModel(List<Contact> contacte){
        listaContacte.clear();
        for(Contact c: contacte){
            listaContacte.addElement(c);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListaContacte = new javax.swing.JList<>();
        SearchBar = new javax.swing.JTextField();
        CBOrdonare = new javax.swing.JComboBox<>();
        BtnFiltrare = new javax.swing.JButton();
        CBFiltrare = new javax.swing.JComboBox<>();
        BtnOrdonare = new javax.swing.JButton();
        BtnAdaugare = new javax.swing.JButton();
        BtnModificare = new javax.swing.JButton();
        BtnStergere = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnDeschidere = new javax.swing.JMenuItem();
        btnSalvare = new javax.swing.JMenuItem();
        btnIesire = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnInregistrare = new javax.swing.JMenuItem();
        btnDespre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(ListaContacte);

        CBOrdonare.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dupa Nume", "Dupa Prenume", "Dupa Numar de Telefon", "Dupa Data Nasterii" }));

        BtnFiltrare.setText("Filtreaza");
        BtnFiltrare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFiltrareActionPerformed(evt);
            }
        });

        CBFiltrare.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Numar Fix", "Numar Mobil", "Nascuti Astazi", "Nascuti Luna Trecuta" }));
        CBFiltrare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBFiltrareActionPerformed(evt);
            }
        });

        BtnOrdonare.setText("Ordoneaza");
        BtnOrdonare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOrdonareActionPerformed(evt);
            }
        });

        BtnAdaugare.setText("Adauga contact");
        BtnAdaugare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdaugareActionPerformed(evt);
            }
        });

        BtnModificare.setText("Modifica contact");
        BtnModificare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificareActionPerformed(evt);
            }
        });

        BtnStergere.setText("Sterge contact");
        BtnStergere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStergereActionPerformed(evt);
            }
        });

        jMenu1.setText("Fisiere");

        btnDeschidere.setText("Deschidere");
        btnDeschidere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeschidereActionPerformed(evt);
            }
        });
        jMenu1.add(btnDeschidere);

        btnSalvare.setText("Salvare");
        jMenu1.add(btnSalvare);

        btnIesire.setText("Iesire");
        jMenu1.add(btnIesire);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajutor");

        btnInregistrare.setText("Inregistrare");
        jMenu2.add(btnInregistrare);

        btnDespre.setText("Despre");
        jMenu2.add(btnDespre);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnAdaugare)
                                .addGap(43, 43, 43)
                                .addComponent(BtnModificare, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(BtnStergere, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SearchBar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CBOrdonare, 0, 163, Short.MAX_VALUE)
                            .addComponent(CBFiltrare, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnFiltrare, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(BtnOrdonare, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnFiltrare)
                    .addComponent(CBFiltrare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBOrdonare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnOrdonare))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnModificare)
                    .addComponent(BtnAdaugare)
                    .addComponent(BtnStergere))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filtrareOrdonare(){
        String s = SearchBar.getText().trim();
        Criteriu_Filtrare cf = (Criteriu_Filtrare) CBFiltrare.getSelectedItem();
        Criteriu_Ordonare co = (Criteriu_Ordonare) CBOrdonare.getSelectedItem();
        
        contacteAfisate = agenda.getListDeAfisat(cf, s, co);
        refreshModel(contacteAfisate);
    }
    private void btnDeschidereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeschidereActionPerformed
        //de implementat jFileChooser pentru baza de date
    }//GEN-LAST:event_btnDeschidereActionPerformed

    private void CBFiltrareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBFiltrareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBFiltrareActionPerformed

    private void BtnFiltrareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFiltrareActionPerformed
        filtrareOrdonare();
    }//GEN-LAST:event_BtnFiltrareActionPerformed

    private void BtnOrdonareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOrdonareActionPerformed
        filtrareOrdonare();
    }//GEN-LAST:event_BtnOrdonareActionPerformed

    private void BtnAdaugareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdaugareActionPerformed
        // de implementat gui pentru fereastra de inregistrare
    }//GEN-LAST:event_BtnAdaugareActionPerformed

    private void BtnModificareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificareActionPerformed
        // same as above
    }//GEN-LAST:event_BtnModificareActionPerformed

    private void BtnStergereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStergereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnStergereActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhoneBookManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhoneBookManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhoneBookManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhoneBookManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhoneBookManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdaugare;
    private javax.swing.JButton BtnFiltrare;
    private javax.swing.JButton BtnModificare;
    private javax.swing.JButton BtnOrdonare;
    private javax.swing.JButton BtnStergere;
    private javax.swing.JComboBox<String> CBFiltrare;
    private javax.swing.JComboBox<String> CBOrdonare;
    private javax.swing.JList<Contact> ListaContacte;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JMenuItem btnDeschidere;
    private javax.swing.JMenuItem btnDespre;
    private javax.swing.JMenuItem btnIesire;
    private javax.swing.JMenuItem btnInregistrare;
    private javax.swing.JMenuItem btnSalvare;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
